package com.cwjcsu.common.crypto;

import java.io.*;
import java.util.Properties;

public final class PasswordFile {
	public static final String algorithm = "des";
	
	private PasswordFile(){
		
	}
	
	public static String loadPassword(InputStream fis) throws IOException {
		Properties props = new Properties();
		try {
			props.load(fis);
			String raw = props.getProperty("password");
			if (raw == null)
				throw new RuntimeException("Not a password file");
			if (raw.startsWith("{" + algorithm + "}")) {
				String encrypted = raw.substring(algorithm.length() + 2);
				return DesCipher.decrypt(encrypted);
			} 
		} catch (IOException e) {
			throw e;
		} 
		return null;
	}

	public static String loadPassword(String file) throws IOException {
		Properties props = new Properties();
		InputStream is = null;
		OutputStream os = null;
		try {
			is = new FileInputStream(file);
			props.load(is);
			String raw = props.getProperty("password");
			if (raw == null)
				throw new RuntimeException("Not a password file");
			if (raw.startsWith("{" + algorithm + "}")) {
				String encrypted = raw.substring(algorithm.length() + 2);
				return DesCipher.decrypt(encrypted);
			} else {// 明文
				String encrypted = DesCipher.encrypt(raw);
				props.setProperty("password", "{" + algorithm + "}" + encrypted);
				os = new FileOutputStream(file);
				props.store(os, "Generated by Skybility");
				return raw;
			}
		} catch (IOException e) {
			throw e;
		} finally {
			if (is != null)
				is.close();
			if (os != null)
				os.close();
		}

	}

	public static void savePassword(String file, String newPassword) throws IOException {
		Properties props = new Properties();
		InputStream is = null;
		OutputStream os = null;
		try {
			String encrypted = DesCipher.encrypt(newPassword);
			props.setProperty("password", "{" + algorithm + "}" + encrypted);
			os = new FileOutputStream(file);
			props.store(os, "Generated by Skybility");
		} catch (IOException e) {
			throw e;
		} finally {
			if (is != null)
				is.close();
			if (os != null)
				os.close();
		}
	}

}
